SELECT * FROM Genre;

SELECT 
    COLUMN_NAME,
    IS_NULLABLE,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'Genre' AND IS_NULLABLE = 'YES';

ALTER TABLE Genre 
ALTER COLUMN Name NVARCHAR (120) NOT NULL;