SELECT * FROM Customer;

SELECT * FROM Customer
WHERE CustomerId IS NULL
OR FirstName IS NULL 
OR LastName IS NULL
OR Company IS NULL
OR Address IS NULL
OR City IS NULL
OR State IS NULL
OR Country IS NULL
OR PostalCode IS NULL
OR PostalCode IS NULL
OR Phone IS NULL
OR Fax IS NULL
OR Email IS NULL
OR SupportRepId IS NULL;

UPDATE Customer
SET Company = ISNULL(Company, 'No tiene compañia'),
	State = ISNULL(State, 'NN'),
	PostalCode = ISNULL (PostalCode, 0),
	Phone = ISNULL(Phone, 0),
	Fax = ISNULL (Fax, 0);

SELECT 
    COLUMN_NAME,
    IS_NULLABLE,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'customer' AND IS_NULLABLE = 'YES';

ALTER TABLE customer
ALTER COLUMN FirstName NVARCHAR(40) NOT NULL;

ALTER TABLE customer
ALTER COLUMN Company NVARCHAR(80) NOT NULL;

ALTER TABLE customer
ALTER COLUMN Address NVARCHAR(70) NOT NULL;

ALTER TABLE customer
ALTER COLUMN City NVARCHAR(40) NOT NULL;

ALTER TABLE customer
ALTER COLUMN State NVARCHAR(40) NOT NULL;

ALTER TABLE customer
ALTER COLUMN Country NVARCHAR(80) NOT NULL;

ALTER TABLE customer
ALTER COLUMN PostalCode NVARCHAR(10) NOT NULL;

ALTER TABLE customer
ALTER COLUMN Phone NVARCHAR(24) NOT NULL;

ALTER TABLE customer
ALTER COLUMN Fax NVARCHAR(24) NOT NULL;

ALTER TABLE Customer
ALTER COLUMN SupportRepId INT NOT NULL;
