SELECT * FROM Artist;

SELECT 
    COLUMN_NAME,
    IS_NULLABLE,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'Artist' AND IS_NULLABLE = 'YES';

ALTER TABLE Artist 
ALTER COLUMN Name NVARCHAR (120) NOT NULL;